### ISSUE TITLE
Breaking changes due to tweepy 4.0.0 version upgrade (AttributeError: 'tweepy' has no attribute 'StreamListener')

### ISSUE THREAD

**Issue by simonseo** [konlpy/konlpy#368]
### Cause
tweepy just released [a new version](https://github.com/tweepy/tweepy/releases/tag/v4.0.0) 17 hours ago:
> StreamListener has been merged into Stream (see Breaking Changes section)

### Symptom
As a result, using the `twitter` module in konlpy version 0.5.2 leads to the following error:
```
AttributeError: 'tweepy' has no attribute 'StreamListener'
```
### Solution
For those experiencing the same problem, I suggest fixing `tweepy` version to something between `3.7.0` and `3.10.0`.

**Comment by gunggmee** [comment]
Your proposed solution fixed my problem. Thank you.

By the way, I've just found that the current main branch doesn't depend on `tweepy` anymore, since around this commit: 7f7bda4.

**Comment by hexists** [comment]
@e9t @minhoryang 

안녕하세요~
[pypi maintainer](https://pypi.org/project/konlpy/#files) 부분을 보고 멘션 남깁니다.

저도 최근에 konlpy를 설치하다보니 tweepy 버전 문제로 설치가 안되더라고요. [Changelog](https://docs.tweepy.org/en/stable/changelog.html), [39abff4](https://github.com/tweepy/tweepy/commit/39abff4520e291180425ac2219d1d8597ac5da96)

그리고 위 내용처럼 master branch에는 tweepy를 사용하는 부분이 제거되어 있는데요. https://github.com/konlpy/konlpy/commit/7f7bda496424140451c4ec0b08e2d77bac6c1726
해당 내용으로 release 해주실 수 있을까요?
긍정적인 검토 부탁드립니다.

-----

@e9t, @minhoryang

I'm writing this comment, after I checked you two are maintainers of konlpy in [pypi](https://pypi.org/project/konlpy/#files).
Recently I couldn't install konlpy due to tweepy version issues. [Changelog](https://docs.tweepy.org/en/stable/changelog.html), [39abff4](https://github.com/tweepy/tweepy/commit/39abff4520e291180425ac2219d1d8597ac5da96)

As https://github.com/konlpy/konlpy/issues/368#issuecomment-927298906 mentioned, Tweepy has been removed from the master branch.

Could you please release this master branch?

Please give me a positive answer.

**Comment by combacsa** [comment]
Hello, @simonseo . Could you please check if this issue could be resolved with `0.6.0` release? Thanks in advance.

* https://pypi.org/project/konlpy/0.6.0/
* https://github.com/konlpy/konlpy/releases/tag/v0.6.0

**Comment by OrianeN** [comment]
I have tested the installation of my project using konlpy 0.6.0 without requiring tweepy, and it's working ! (Windows 10 - Python 3.8.6 + WSL Ubuntu 20.04 - Python 3.8.10)

**Comment by combacsa** [comment]
@OrianeN Thank you for sharing your test result :)

Waiting for @simonseo's reply to make sure that if we could safely close this issue.

**Comment by simonseo** [comment]
This problem was resolved! For some reason I didn't see all the mentions.
